kind: pipeline
type: docker
name: default

#clone:
#  disable: true

steps:
  - name: 编译步骤
    image: alpine
    settings:
      add_host: www.laiyouxu.club:172.22.209.43
    commands:
      - echo hello drone